# SecureVault.spec – PyInstaller build spec (Windows + macOS)
# Generated for SecureVault 1.0.0
# Run:  pyinstaller SecureVault.spec

import os
import sys

block_cipher = None
IS_MAC = sys.platform == "darwin"
IS_WIN = sys.platform == "win32"

# Icon paths (generated by create_icon.py)
ICON = os.path.join("assets", "icon.icns" if IS_MAC else "icon.ico")
if not os.path.isfile(ICON):
    ICON = None   # build without icon if not yet generated

a = Analysis(
    ["main.py"],
    pathex=["."],
    binaries=[],
    datas=[],
    hiddenimports=[
        "app_paths",
        "updater",
        "Authentication",
        "vault_storage",
        "Vault_details",
        "password_strength",
        "Generator",
        "now_playing",
        # Cryptography internals that PyInstaller sometimes misses
        "cryptography.hazmat.primitives.kdf.pbkdf2",
        "cryptography.hazmat.primitives.hashes",
        "cryptography.hazmat.backends",
        "cryptography.hazmat.backends.openssl",
        # PySide6 modules
        "PySide6.QtCore",
        "PySide6.QtGui",
        "PySide6.QtWidgets",
        "PySide6.QtSvg",
        "PySide6.QtOpenGL",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "unittest", "email", "html", "http", "urllib"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="SecureVault",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=IS_MAC,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=ICON,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="SecureVault",
)

# macOS .app bundle
if IS_MAC:
    app = BUNDLE(
        coll,
        name="SecureVault.app",
        icon=ICON,
        bundle_identifier="com.securevault.app",
        info_plist={
            "CFBundleName":             "SecureVault",
            "CFBundleDisplayName":      "SecureVault",
            "CFBundleVersion":          "1.0.0",
            "CFBundleShortVersionString": "1.0.0",
            "NSHighResolutionCapable":  True,
            "NSRequiresAquaSystemAppearance": False,
            "LSMinimumSystemVersion":   "11.0",
            "NSAppleEventsUsageDescription":
                "SecureVault uses Apple Events to detect the currently playing track.",
        },
    )
